#!/bin/sh /etc/rc.common
# Authenticating utility for auth.tsinghua.edu.cn
# This init script is used explicitly with OpenWRT
# https://github.com/z4yx/GoAuthing/blob/master/docs/init.d/goauthing%40

USE_PROCD=1
START=98
PROG="/usr/bin/goauthing"
SERV=goauthing  # UCI config at /etc/config/goauthing

generate_command() {
CMD="\
\"$PROG\" $1 deauth; \
\"$PROG\" $1 auth; \
\"$PROG\" $1 online; \
"
}

start_instance() {
  local username password
  config_get username config username
  config_get password config password
  local args="-u $username -p $password"

  generate_command "$args"

  procd_open_instance
  procd_set_param command sh
  procd_append_param command -c "$CMD"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn
  procd_close_instance
}

start_service() {
  config_load "$SERV"
  config_get_bool enabled config enabled 0
  if [ "$enabled" == "0" ]; then
    return
  fi
  start_instance
}

stop_service() {
  "$PROG" deauth
}

# Custom reload function to restart the service
service_triggers() {
  procd_add_reload_trigger "goauthing"
  procd_add_interface_trigger "interface.*.up" wan /etc/init.d/goauthing reload
}

reload_service() {
  stop
  start
}
