name: Compile auth-thu LuCI App

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  Get-Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Current Version in Makefile
        id: version
        run: |
          echo "version=$(grep 'PKG_VERSION:=' ./Makefile |awk -F ':=' '{print $2}')" >> $GITHUB_OUTPUT
          echo "Current Makefile Version: $(grep 'PKG_VERSION:=' ./Makefile |awk -F ':=' '{print $2}')"

  Compile:
    runs-on: ubuntu-latest
    needs: Get-Version
    steps:
      - name: Clone auth-thu Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Apt Update
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install curl git tar zstd

      - name: Install OpenWrt SDK
        run: |
          curl -SLk --connect-timeout 30 --retry 2 "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" -o "/tmp/SDK.tar.bz2"
          cd /tmp
          tar xjf SDK.tar.bz2
          mv "OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64" "SDK"

      - name: Install OpenWrt SNAPSHOT SDK
        run: |
          curl -SLk --connect-timeout 30 --retry 2 "https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst" -o "/tmp/SNAPSDK.tar.zst"
          cd /tmp
          zstd -d SNAPSDK.tar.zst
          tar xf SNAPSDK.tar
          mv "openwrt-sdk-x86-64_gcc-14.3.0_musl.Linux-x86_64" "SNAPSDK"

      - name: Copy auth-thu Source Codes
        run: |
          mkdir -p /tmp/SDK/package/luci-app-auth-thu
          mkdir -p /tmp/SNAPSDK/package/luci-app-auth-thu
          rsync -avh "." "/tmp/SDK/package/luci-app-auth-thu"
          rsync -avh "." "/tmp/SNAPSDK/package/luci-app-auth-thu"

      - name: Install po2lmo
        run: |
          python -m pip install --upgrade pip
          pip install po2lmo

      - name: Compile auth-thu IPK
        run: |
          cd /tmp/SDK
          ./scripts/feeds update -a
          ./scripts/feeds install luci-app-auth-thu
          echo 'CONFIG_PACKAGE_luci-app-auth-thu=y'>.config
          make defconfig
          make package/luci-app-auth-thu/compile V=99

      - name: Compile auth-thu APK
        run: |
          cd /tmp/SNAPSDK
          ./scripts/feeds update -a
          ./scripts/feeds install luci-app-auth-thu
          echo 'CONFIG_PACKAGE_luci-app-auth-thu=y'>.config
          make defconfig
          make package/luci-app-auth-thu/compile V=99

      - name: Create Version Info
        run: |
          mkdir -p ./artifacts
          echo "v${{ needs.Get-Version.outputs.version }}" > ./artifacts/version.txt

      - name: Move Packages to Upload Directory
        run: |
          # Copy IPK from legacy SDK
          cp /tmp/SDK/bin/ar71xx/packages/base/luci-app-auth-thu_*_all.ipk "./artifacts/"
          cp /tmp/SDK/bin/ar71xx/packages/base/luci-i18n-auth-thu-*_all.ipk "./artifacts/"

          # Copy APK from SNAPSHOT SDK
          cp /tmp/SNAPSDK/bin/packages/x86_64/base/luci-app-auth-thu-*.apk "./artifacts/"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: auth-thu-Packages-v${{ needs.Get-Version.outputs.version }}
          path: |
            ./artifacts/*
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/*
          name: Release v${{ needs.Get-Version.outputs.version }}
          tag_name: ${{ github.ref_name }}
